### ISSUE TITLE
IBRS enabled for Kernel space:  UNKNOWN 

### ISSUE THREAD

**Issue by corradoventu** [speed47/spectre-meltdown-checker#171]
On my laptop
```
corrado@corrado-HP-p4-bb-0319:~$ inxi -SCx
System:    Host: corrado-HP-p4-bb-0319 Kernel: 4.15.0-13-generic x86_64
           bits: 64 gcc: 7.3.0
           Desktop: Gnome 3.28.0 (Gtk 3.22.29-2ubuntu1)
           Distro: Ubuntu Bionic Beaver (development branch)
CPU:       Dual core Intel Core i5-4210U (-MT-MCP-) 
           arch: Haswell rev.1 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9577
           clock speeds: max: 2700 MHz 1: 1003 MHz 2: 1319 MHz 3: 1109 MHz
           4: 1378 MHz
corrado@corrado-HP-p4-bb-0319:~$ 
```
I'm using your tool (thanks a lot) and I see:

```
 * Mitigation 1
  * Kernel is compiled with IBRS/IBPB support:  YES 
  * Currently enabled features
    * IBRS enabled for Kernel space:  UNKNOWN 
    * IBRS enabled for User space:  UNKNOWN 
    * IBPB enabled:  UNKNOWN 
```
I have intel-microcode installed 

```
 corrado@corrado-HP-p4-bb-0319:~$ apt policy intel-microcode
intel-microcode:
  Installed: 3.20180312.0~ubuntu18.04.1
  Candidate: 3.20180312.0~ubuntu18.04.1
```
I wonder about this 'UNKNOWN' ... i'ts a problem?
thanks again for your tool
